---
bibliography: references.bib
---
# Introduction {#sec-intro}

Universal access  essential medicines is a cornerstone of effective healthcare systems, yet ensuring equitable availability of these vital medications remains an urgent global challenge[@quick2003essential;@world2004annual]. Across continents, especially in Africa and Asia, many nations grapple with restricted access due to factors like unaffordability and suboptimal supply chain management [@world2004medicines]. A survey conducted across eight sub-Saharan African countries indicated that there were  unacceptably low availability of essential medicines.The mean availability of 12 priority essential medicines for women ranged from 22% to 40% and from 28% to 57% for children [@droti2019poor]. However, the issue of drug shortages extends beyond developing countries, with instances reported in the United States and Europe, adversely impacting healthcare systems and compromising patient care quality [@fox2003managing, @kaakeh2011impact; @johnson2011drug; @huys2013european;@le2011prevalence].

The consequences of drug shortages are felt both financially within the healthcare sector and in terms of the quality of patient care [@alspach2012drug; @kaakeh2011impact;@kaakeh2011impact; @baumer2004national].The consequences extend across patients, providers, healthcare institutions, and research programs. Patients face delays or cancellations of treatments, substandard care due to the unavailability of optimal therapies, and increased costs in a secondary "grey market." Compromised patient safety, complications, prolonged hospital stays, and even deaths have been reported [@alspach2012drug;].Addressing these shortages is crucial to preserving the quality of patient care and ensuring the effectiveness of healthcare delivery. Thus, a smoothly operating pharmaceutical supply chain is essential to ensure timely access to essential medicines, making accurate demand forecasting an indispensable component.

An efficient pharmaceutical supply chain is vital for timely access to essential health commodities. One of the most crucial components of such a supply chain is a well-defined demand forecasting process. Forecasting accurately the future demand for essential medicines provides valuable insights for anticipating future healthcare requirements including procurement and replenishment of inventory[@subramanian2021effective]. Despite the significance of forecasting for supply chain management, pharmaceutical product forecasting remains a complex endeavor influenced by a multitude of factors. Key considerations include the availability of data, the specific position within the supply chain, and the nuanced understanding of contributing elements. The position within the supply chain introduces unique challenges and dynamics, requiring tailored forecasting approaches. Additionally, a nuanced understanding of contributing elements involves grasping intricate factors that impact forecasting accuracy, such as market trends, regulatory changes, and external influences. Schneider, Wilson, and Rosenbeck (2010) and Hyndman and Athanasopoulos (2018) highlight the intricate nature of pharmaceutical forecasting, emphasizing the need for a comprehensive approach that incorporates these multifaceted aspects to enhance supply chain management effectiveness[@schneider2010pharmaceutical; @hyndman2018forecasting].


The Ethiopian pharmaceutical sector's distinct characteristics, marked by a diverse array of medicines and unique data challenges stemming from service delivery points, staff capacity limitations, communication hurdles, prolonged procurement and distribution lead times, poor forecast accuracy, and policy intricacies, necessitates tailored forecasting strategies that cater to the nation's specific context [@boche2022procurement]. In this context, a comprehensive exploration of effective forecasting models that align with Ethiopia's pharmaceutical landscape is paramount to mitigating stock outs and enhancing healthcare delivery. The implications of pharmaceutical demand forecasting extend beyond financial considerations to societal well-being [@rostami2022forecasting]. In Ethiopia, a country undergoing demographic and healthcare evolution, precise demand forecasting assumes immense importance for resource allocation, supply chain optimization, and policy formulation. With mounting interest in refining demand forecasting in Ethiopia's pharmaceutical sector, this study seeks to contribute to existing knowledge by investigating and recommending proficient demand forecasting methods. Our investigation centers on the application of mean, naive, exponential smoothing, regression, and ARIMA models to bolster forecast accuracy and effectiveness. This paper aims to forecast the demand for selected pharmaceuticals in EPSS over the next 12 months by utilizing various forecasting models and integrating predictors. The integration of predictors with the models will be examined to determine whether they enhance the forecasting accuracy. These predictors are derived from a historical analysis of events in Ethiopia over the last 5 years that have impacted pharmaceutical sales in EPSS. These events include COVID-19, conflicts in the country, disease campaigns, budget closures, budget releases, and physical inventory, all of which, in varying degrees, influence the demand for pharmaceuticals in Ethiopia.


The current paper offers the following contributions we aim at forecasting pharmaceutical sales over a 12-month period these models aim to enhance the accuracy and reliability of demand predictions within the context of EPSS. Moreover an essential contribution lies in the identification of key factors influencing pharmaceutical sales. The study develops a model that effectively incorporates these driving factors, providing a more nuanced and comprehensive approach to demand prediction. We generate forecasts and evaluate model performance using the Root Mean Squared Error (RMSE), Root Mean Squared Scaled Error (RMSSE) and Mean Absolute Error (MAE), Mean Absolute Scaled Error (MASE), Crips and Winkler are used to assess probabilistic forecast accuracy. 


#how you know the forecasting accutacy problem and provide eveidence about the forecasting problems 
# most forecast focus on point forecast and we want to focus on probablistic forecast
# i will write the contribution of the reearch rather than these objectives 

This research is guided by several objectives:

1. Evaluate the robustness of various forecasting models for pharmaceutical demand prediction within EPSS.
2. Identify pharmaceuticals that exhibit superior forecast accuracy under specific models.
3. Assess the performance of forecast accuracy metrics to gauge the efficacy of selected models.
4. Test the incorporation of diverse predictors affecting forecasts and evaluate resulting forecasting accuracy.
In pursuing these objectives, this study endeavors to elevate the precision and reliability of pharmaceutical demand forecasting, thereby contributing to optimized supply chain management and enhanced healthcare outcomes in Ethiopia.



