---
title: "The missing puzzle piece: Contextual insights for enhanced pharmaceutical supply chain forecasting"
# author:
#   - name: Arebu Issa Bilal
#     email: arebu.issa@aau.edu.et
#     affiliations:
#         - id: Addis 
#           name: Addis Ababa University
#           department: Department of Pharmaceutics and Social Pharmacy, School of Pharmacy
#           country: Ethiopia.
#     attributes:
#         corresponding: true
#   - name: Bahman Rostami-Tabar
#     email: rostami-tabarb@cardiff.ac.uk
#     affiliations:
#         - id: carbs
#           name: Cardiff University
#           department: Data Lab for Social Good Reserach Group, Cardiff Business School 
#           country: UK.
#   - name: Harsha Halgamuwe Hewage
#     email: HalgamuweHewageHR@cardiff.ac.uk
#     affiliations:
#         - ref: carbs
#   - name: Umit Sezer Bititci 
#     email: U.S.Bititci@hw.ac.uk
#     affiliations:
#         - id: herio 
#           name: Heriot-Watt University
#           department: Edinburgh Business School, Heriot-Watt University
#           country: UK.
#   - name: Teferi Gedif Fenta
#     email: tgedif@gmail.com
#     affiliations:
#         - ref: Addis 

abstract: |
  Accurate forecasting in pharmaceutical supply chains is critical for ensuring the continuous availability of essential medicines, particularly in developing countries where resource constraints and logistical challenges are more pronounced. Effective demand forecasting supports procurement and inventory management, which in turn could help to prevent stockouts, reduce wastage due to overstocking, and enhance overall healthcare delivery. In such settings, reliable forecasts, that acknowledge uncertainties, are essential to ensure that limited resources are used efficiently to meet health needs. 
  Despite advancements in forecasting, significant gaps remain in effective forecasting in poor resource countries. Most existing literature on pharmaceutical supply chain forecasting focuses primarily on point estimation of consumption while neglecting the inherent uncertainty of these forecasts. Additionally, these studies often rely solely on historical consumption data without considering the broader context that influences consumption. Furthermore, many works lack rigorous methodological design, transparency, and reproducibility. This study addresses these gaps by integrating domain-specific knowledge, gathered through expert interviews and engagement with key members of the Ethiopian Pharmaceutical Supply Service (EPSS), into forecasting models. Using a dataset spanning five years (December 2017 to July 2022) from EPSS, we developed forecasting models that integrate expert-identified variables such as stock replenishment schedules, fiscal inventory counts, and disease outbreaks. Evaluation metrics including Mean Absolute Scaled Error (MASE), Root Mean Squared Scaled Error (RMSSE), and Continuous Ranked Probability Score (CRPS) are used to report forecast accuracy. The findings underscore the significance of contextual data in developing robust forecasting models that are adaptable to complex, real-world conditions. Our results also highlight the effectiveness of foundational time series models for forecasting. These models are particularly appealing for resource-constrained countries that may lack advanced analytical expertise. To promote usability, generalizability, and reproducibility, we share the complete dataset and code in R and Python, and the entire paper is written in Quarto via a GitHub repository to facilitate these practices.
  
  
keywords:
  - Forecasting
  - Pharmaceutical supply chain
  - Domain knowlege
  - Forecast accuracy
  - Developing countries
bibliography: references.bib
execute:
  echo: false
  message: false
  warning: false
  pdf-engine: pdflatex
  prefer-html: true
  cache: true
format:
  html:
    number-sections: true
  docx:
    number-sections: true
  elsevier-pdf:
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{todonotes,mathtools,bm,amsmath,mathpazo}
        \mathtoolsset{showonlyrefs}
        \setlength{\parindent}{0cm}
    journal:
      name: International Journal of Production Research
      formatting: preprint
      model: 3p
      cite-style: authoryear
---

```{r}
#| label: setup
#| include: false
library(fpp3)
library(kableExtra)
library(tidyverse)
library(kableExtra)
library(ggthemes)
library(patchwork)
library(readr)
library(forcats)
# Color blind color palettes
options(
  ggplot2.discrete.colour = c("#D55E00", "#0072B2","#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#F0E442"),
  ggplot2.discrete.fill = c("#D55E00", "#0072B2","#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#F0E442")
)
# Few theme
ggplot2::theme_set(ggthemes::theme_few())



```

```{r intro, child="01-introduction.qmd"}

```

```{r literature, child="02-literature.qmd"}

```

```{r experiment, child="03-experiment.qmd"}

```

```{r results, child="04-results.qmd"}

```

```{r conclusion, child="05-conclusion.qmd"}

```

# Reproducibility {.unnumbered}

We use R and Python for model development and accuracy evaluation. The paper is written in Quarto, and all code, data, and files will be shared in a GitHub repository upon acceptance for publication.

# References {#references .unnumbered}
